name: Octo Organization CI

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Tile
        uses: prsh-singh834006/validate-pr-title@0.0.1


